"""NFL team aliases, city names, nicknames, and slang.

Keyed by lowercase alias -> canonical team_abbr. Used by EntityResolver for
fuzzy/alias matching of team mentions.
"""

TEAM_ALIASES = {
    # City names to abbreviations
    "arizona": "ARI",
    "atlanta": "ATL",
    "baltimore": "BAL",
    "buffalo": "BUF",
    "carolina": "CAR",
    "chicago": "CHI",
    "cincinnati": "CIN",
    "cleveland": "CLE",
    "dallas": "DAL",
    "denver": "DEN",
    "detroit": "DET",
    "green bay": "GB",
    "houston": "HOU",
    "indianapolis": "IND",
    "jacksonville": "JAX",
    "kansas city": "KC",
    "las vegas": "LV",
    "los angeles rams": "LA",
    "los angeles chargers": "LAC",
    "los angeles": "LA",
    "miami": "MIA",
    "minnesota": "MIN",
    "new england": "NE",
    "new orleans": "NO",
    "new york giants": "NYG",
    "new york jets": "NYJ",
    "new york": "NYG",
    "philadelphia": "PHI",
    "pittsburgh": "PIT",
    "san francisco": "SF",
    "seattle": "SEA",
    "tampa bay": "TB",
    "tampa": "TB",
    "tennessee": "TEN",
    "washington": "WAS",

    # Full team names
    "kansas city chiefs": "KC",
    "san francisco 49ers": "SF",
    "new england patriots": "NE",
    "green bay packers": "GB",
    "dallas cowboys": "DAL",
    "pittsburgh steelers": "PIT",
    "arizona cardinals": "ARI",
    "atlanta falcons": "ATL",
    "baltimore ravens": "BAL",
    "buffalo bills": "BUF",
    "carolina panthers": "CAR",
    "chicago bears": "CHI",
    "cincinnati bengals": "CIN",
    "cleveland browns": "CLE",
    "denver broncos": "DEN",
    "detroit lions": "DET",
    "houston texans": "HOU",
    "indianapolis colts": "IND",
    "jacksonville jaguars": "JAX",
    "las vegas raiders": "LV",
    "miami dolphins": "MIA",
    "minnesota vikings": "MIN",
    "new orleans saints": "NO",
    "philadelphia eagles": "PHI",
    "seattle seahawks": "SEA",
    "tampa bay buccaneers": "TB",
    "tennessee titans": "TEN",
    "washington commanders": "WAS",

    # Nicknames only
    "cardinals": "ARI",
    "falcons": "ATL",
    "ravens": "BAL",
    "bills": "BUF",
    "panthers": "CAR",
    "bears": "CHI",
    "bengals": "CIN",
    "browns": "CLE",
    "cowboys": "DAL",
    "broncos": "DEN",
    "lions": "DET",
    "packers": "GB",
    "texans": "HOU",
    "colts": "IND",
    "jaguars": "JAX",
    "jags": "JAX",
    "chiefs": "KC",
    "raiders": "LV",
    "rams": "LA",
    "chargers": "LAC",
    "dolphins": "MIA",
    "vikings": "MIN",
    "patriots": "NE",
    "saints": "NO",
    "giants": "NYG",
    "jets": "NYJ",
    "eagles": "PHI",
    "steelers": "PIT",
    "49ers": "SF",
    "seahawks": "SEA",
    "buccaneers": "TB",
    "bucs": "TB",
    "titans": "TEN",
    "commanders": "WAS",
    "redskins": "WAS",

    # Common nicknames/slang
    "niners": "SF",
    "pack": "GB",
    "pats": "NE",
    "hawks": "SEA",
    "birds": "PHI",
    "fins": "MIA",
    "bolts": "LAC",
    "big blue": "NYG",
    "america's team": "DAL",
    "g-men": "NYG",
}

__all__ = ["TEAM_ALIASES"]
