name: Extract NFL News URLs

on:
  schedule:
    # Every 15 minutes
    - cron: '*/15 * * * *'
  
  workflow_dispatch:  # Allow manual triggers

env:
  PYTHON_VERSION: '3.11'

jobs:
  extract-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/functions/news_extraction/requirements.txt
      
      - name: Extract news URLs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python src/functions/news_extraction/scripts/extract_news_cli.py \
            --days-back 1 \
      
      - name: Report status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ News extraction completed successfully"
          else
            echo "❌ News extraction failed"
            exit 1
          fi
