name: Load NFL Players (Daily)

on:
  schedule:
    # Daily at 8:00 AM ET = 12:00 PM UTC (EST) or 12:00 PM UTC (EDT)
    - cron: '0 12 * * *'
  
  workflow_dispatch:  # Allow manual triggers

env:
  PYTHON_VERSION: '3.11'

jobs:
  load-players:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/functions/data_loading/requirements.txt
      
      - name: Load players
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python src/functions/data_loading/scripts/players_cli.py --log-level INFO --active-only --min-last-season 2025
      
      - name: Report status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Players loaded successfully"
          else
            echo "❌ Players load failed"
            exit 1
          fi
