name: Group Similar Stories

on:
  schedule:
    # Every 10 minutes
    - cron: '*/10 * * * *'
  
  workflow_dispatch:  # Allow manual triggers

env:
  PYTHON_VERSION: '3.11'

jobs:
  group-stories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/functions/story_grouping/requirements.txt
      
      - name: Group stories
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python src/functions/story_grouping/scripts/group_stories_cli.py \
          --limit 25 --days 14 --threshold 0.82
          
      - name: Report status
        if: always()
        run: | 
          if [ $? -eq 0 ]; then
            echo "✅ Story grouping completed successfully"
          else
            echo "❌ Story grouping failed"
            exit 1
          fi
